- name: Preparation Setup Zimbra on Rocky Linux
  hosts: zimbra
  become: yes
  vars:
    hostname: mail
    domain: afatyo.web.id
    ip_address: 192.168.13.23

  tasks:
    # === Basic preparation ===
    - name: Disable SELinux permanently
      ansible.builtin.replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=disabled'

    - name: Set SELinux enforcing 0 (runtime)
      ansible.builtin.command: setenforce 0
      ignore_errors: yes

    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Configure /etc/hosts
      ansible.builtin.copy:
        dest: /etc/hosts
        content: |
          127.0.0.1   localhost
          {{ ip_address }}   {{ hostname }}.{{ domain }}   {{ hostname }}

    - name: Set system hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.{{ domain }}"

    - name: Update system packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Enable EPEL repo
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install Zimbra dependencies (Rocky 9)
      ansible.builtin.dnf:
        name:
          - perl
          - perl-core
          - wget
          - screen
          - openssh-clients
          - openssh-server
          - unzip
          - nmap
          - sed
          - nc
          - sysstat
          - libaio
          - rsync
          - telnet
          - libssh2
          - libnsl
          - libicu
          - tar
          - mod_ssl
          - perl-Encode-HanExtra
          - pcre-devel
          - bzip2-devel
          - ncurses-compat-libs
          - swaks
          - vim
          - bind
          - bind-utils
        state: present
        enablerepo: epel
      when: ansible_distribution_major_version | int == 9

    - name: Install Zimbra dependencies (Rocky 8)
      ansible.builtin.dnf:
        name:
          - perl
          - perl-core
          - wget
          - screen
          - openssh-clients
          - openssh-server
          - unzip
          - nmap
          - sed
          - nc
          - sysstat
          - libaio
          - rsync
          - telnet
          - libssh2
          - libnsl
          - libicu
          - tar
          - mod_ssl
          - perl-Encode-HanExtra
          - pcre-devel
          - bzip2-devel
          - ncurses-compat-libs
          - swaks
          - vim
          - bind
          - bind-utils
        state: present
        enablerepo: epel
      when: ansible_distribution_major_version | int == 8


    - name: Install aspell (Rocky 9 CRB)
      ansible.builtin.dnf:
        name: aspell
        enablerepo: crb
        state: present
      when: ansible_distribution_major_version | int == 9

    - name: Install aspell (Rocky 8 PowerTools)
      ansible.builtin.dnf:
        name: aspell
        enablerepo: PowerTools
        state: present
      when: ansible_distribution_major_version | int == 8

    # === DNS setup ===
    - name: Overwrite named.conf (Rocky 9 minimal config)
      ansible.builtin.copy:
        dest: /etc/named.conf
        content: |
          options {
              directory "/var/named";
              listen-on port 53 { any; };
              listen-on-v6 port 53 { any; };
              allow-query { any; };
              recursion yes;
              forwarders { 8.8.8.8; 1.1.1.1; };
          };

          logging {
              channel default_debug {
                  file "data/named.run";
                  severity dynamic;
              };
          };

          zone "." IN {
              type hint;
              file "named.ca";
          };

          zone "{{ domain }}" IN {
              type master;
              file "db.{{ domain }}";
              allow-update { none; };
          };
      when: ansible_distribution_major_version | int == 9

    - name: Overwrite named.conf (Rocky 8 default style)
      ansible.builtin.copy:
        dest: /etc/named.conf
        content: |
          options {
              listen-on port 53 { any; };
              listen-on-v6 port 53 { any; };
              directory       "/var/named";
              dump-file       "/var/named/data/cache_dump.db";
              statistics-file "/var/named/data/named_stats.txt";
              memstatistics-file "/var/named/data/named_mem_stats.txt";
              allow-query     { any; };
              recursion yes;
              forwarders { 8.8.8.8; 1.1.1.1; };
          };

          logging {
              channel default_debug {
                  file "data/named.run";
                  severity dynamic;
              };
          };

          zone "." IN {
              type hint;
              file "named.ca";
          };

          zone "{{ domain }}" IN {
              type master;
              file "db.{{ domain }}";
              allow-update { none; };
          };
      when: ansible_distribution_major_version | int == 8

    - name: Create zone file
      ansible.builtin.copy:
        dest: "/var/named/db.{{ domain }}"
        content: |
          $TTL 1D
          @   IN SOA  ns1.{{ domain }}. root.{{ domain }}. (
                                  0       ; serial
                                  1D      ; refresh
                                  1H      ; retry
                                  1W      ; expire
                                  3H )    ; minimum
          @       IN  NS  ns1.{{ domain }}.
          @       IN  MX  0 {{ hostname }}.{{ domain }}.
          ns1     IN  A   {{ ip_address }}
          {{ hostname }} IN  A   {{ ip_address }}
        owner: root
        group: named
        mode: '0644'

    - name: Restart and enable named
      ansible.builtin.systemd:
        name: named
        state: restarted
        enabled: yes

    # === resolv.conf overwrite ===
    - name: Disable and stop systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove systemd-resolved symlink if exists
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      ignore_errors: yes

    - name: Configure resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          search {{ domain }}
          nameserver {{ ip_address }}
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        owner: root
        group: root
        mode: '0644'
